INFO     root:conftest.py:124 Starting test: test_basic_auth[--Not authorized\n].
INFO     root:conftest.py:41 Initializing driver for browser: chrome (Config: chrome).
INFO     root:conftest.py:50 Using user_data_dir: /tmp/user_data_gw0
INFO     root:conftest.py:56 Using debug_port: 9222
INFO     WDM:logger.py:11 xdist worker is: gw0
INFO     WDM:logger.py:11 ====== WebDriver manager ======
INFO     WDM:logger.py:11 Get LATEST chromedriver version for google-chrome
INFO     WDM:logger.py:11 Get LATEST chromedriver version for google-chrome
INFO     WDM:logger.py:11 Driver [/home/runner/.wdm/gw0/drivers/chromedriver/linux64/141.0.7390.122/chromedriver-linux64/chromedriver] found in cache
INFO     root:conftest.py:142 Started recording: tests_recordings/gw0/test_basic_auth[--Not authorized\n]_20251026_135619/test_basic_auth[--Not authorized\n]_20251026_135619.mp4
INFO     root:base_page.py:74 Navigating to URL: https://the-internet.herokuapp.com/.
INFO     root:base_page.py:76 Navigation completed.
INFO     root:base_page.py:55 Waiting for page to load with indicator ('css selector', 'h1.heading') for 10s.
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
INFO     root:base_page.py:60 Page loaded successfully with indicator ('css selector', 'h1.heading').
INFO     root:test_basic_auth_login_scenarios.py:22 Starting Basic Auth test.
INFO     root:basic_auth_page.py:17 .
INFO     root:basic_auth_page.py:25 .
INFO     root:base_page.py:74 Navigating to URL: http://the-internet.herokuapp.com/basic_auth.
INFO     root:base_page.py:76 Navigation completed.
INFO     root:basic_auth_page.py:30 Attempting to get authorization message.
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
ERROR    root:base_page.py:30 Timeout after 10s for locator ('css selector', 'div#content p'): Message: 
Stacktrace:
#0 0x55ba6fc23fea <unknown>
#1 0x55ba6f6a1d06 <unknown>
#2 0x55ba6f6f3e6d <unknown>
#3 0x55ba6f6f4101 <unknown>
#4 0x55ba6f7426b4 <unknown>
#5 0x55ba6f719e3d <unknown>
#6 0x55ba6f73fb3b <unknown>
#7 0x55ba6f719be3 <unknown>
#8 0x55ba6f6e62d2 <unknown>
#9 0x55ba6f6e6f91 <unknown>
#10 0x55ba6fbe79e8 <unknown>
#11 0x55ba6fbeb84f <unknown>
#12 0x55ba6fbceec9 <unknown>
#13 0x55ba6fbec3f5 <unknown>
#14 0x55ba6fbb474f <unknown>
#15 0x55ba6fc10cc8 <unknown>
#16 0x55ba6fc10ea3 <unknown>
#17 0x55ba6fc22f83 <unknown>
#18 0x7f26cd49caa4 <unknown>
#19 0x7f26cd529c6c <unknown>

INFO     root:test_basic_auth_login_scenarios.py:28 Basic Auth test completed successfully.
INFO     root:conftest.py:146 Stopping video recording...
INFO     utils.video_recorder:video_recorder.py:95 Video created: tests_recordings/gw0/test_basic_auth[--Not authorized\n]_20251026_135619/test_basic_auth[--Not authorized\n]_20251026_135619.mp4
INFO     root:conftest.py:102 Quitting driver for browser: chrome.