{"name": "test_basic_auth[--Not authorized\\n]", "status": "passed", "steps": [{"name": "Initialize URL.", "status": "passed", "parameters": [{"name": "username", "value": "''"}, {"name": "password", "value": "''"}], "start": 1761482777818, "stop": 1761482777818}, {"name": "Navigating to URL: 'http://the-internet.herokuapp.com/basic_auth'.", "status": "passed", "steps": [{"name": "Navigating to URL: 'http://the-internet.herokuapp.com/basic_auth'.", "status": "passed", "parameters": [{"name": "url", "value": "'http://the-internet.herokuapp.com/basic_auth'"}], "start": 1761482777819, "stop": 1761482777927}], "parameters": [{"name": "url", "value": "'http://the-internet.herokuapp.com/basic_auth'"}], "start": 1761482777818, "stop": 1761482777927}, {"name": "Get authorization message.", "status": "passed", "steps": [{"name": "Get text of element ('css selector', 'div#content p')", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55ac19f7cfea <unknown>\n#1 0x55ac199fad06 <unknown>\n#2 0x55ac19a4ce6d <unknown>\n#3 0x55ac19a4d101 <unknown>\n#4 0x55ac19a9b6b4 <unknown>\n#5 0x55ac19a72e3d <unknown>\n#6 0x55ac19a98b3b <unknown>\n#7 0x55ac19a72be3 <unknown>\n#8 0x55ac19a3f2d2 <unknown>\n#9 0x55ac19a3ff91 <unknown>\n#10 0x55ac19f409e8 <unknown>\n#11 0x55ac19f4484f <unknown>\n#12 0x55ac19f27ec9 <unknown>\n#13 0x55ac19f453f5 <unknown>\n#14 0x55ac19f0d74f <unknown>\n#15 0x55ac19f69cc8 <unknown>\n#16 0x55ac19f69ea3 <unknown>\n#17 0x55ac19f7bf83 <unknown>\n#18 0x7f15fa29caa4 <unknown>\n#19 0x7f15fa329c6c <unknown>\n\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/allure_commons/_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/selenium-python/selenium-python/pages/base_page.py\", line 113, in get_dynamic_element_text\n    elem = self.wait_for_visibility(locator, timeout)\n  File \"/home/runner/work/selenium-python/selenium-python/pages/base_page.py\", line 70, in wait_for_visibility\n    return self._safe_wait(EC.visibility_of_element_located, locator, timeout)\n  File \"/home/runner/work/selenium-python/selenium-python/pages/base_page.py\", line 28, in _safe_wait\n    return wait.until(ec_method(locator))\n  File \"/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/selenium/webdriver/support/wait.py\", line 138, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "('css selector', 'div#content p')"}, {"name": "timeout", "value": "None"}, {"name": "retry_count", "value": "2"}], "start": 1761482777928, "stop": 1761482788452}], "start": 1761482777927, "stop": 1761482788601}], "attachments": [{"name": "log", "source": "6f39fe6e-f23c-4ee0-8cfd-8c3184b30be5-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "01bbe247-418a-496b-a754-6ce7a14bea97-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "''"}, {"name": "password", "value": "''"}, {"name": "expected_message", "value": "'Not authorized\n'"}], "start": 1761482777818, "stop": 1761482788602, "uuid": "3a796860-ca82-4f21-b754-a80d673f2d2b", "historyId": "42798e6512954325e5980ba5783125cc", "testCaseId": "1a21bc8c1f3aa66587e32fe54490333a", "fullName": "tests.test_basic_auth_login_scenarios.TestBasicAuth#test_basic_auth", "labels": [{"name": "feature", "value": "Basic Auth"}, {"name": "severity", "value": "normal"}, {"name": "story", "value": "Tests Basic Autorization login scenatios"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_basic_auth_login_scenarios"}, {"name": "subSuite", "value": "TestBasicAuth"}, {"name": "host", "value": "runnervmwhb2z"}, {"name": "thread", "value": "5788-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_basic_auth_login_scenarios"}], "titlePath": ["tests", "test_basic_auth_login_scenarios.py", "TestBasicAuth"]}