INFO     root:conftest.py:124 Starting test: test_basic_auth[--Not authorized\n].
INFO     WDM:logger.py:11 xdist worker is: gw1
INFO     WDM:logger.py:11 ====== WebDriver manager ======
INFO     WDM:logger.py:11 Get LATEST chromedriver version for google-chrome
INFO     WDM:logger.py:11 Get LATEST chromedriver version for google-chrome
INFO     WDM:logger.py:11 Driver [/home/runner/.wdm/gw1/drivers/chromedriver/linux64/141.0.7390.122/chromedriver-linux64/chromedriver] found in cache
INFO     root:conftest.py:142 Started recording: tests_recordings/gw1/test_basic_auth[--Not authorized\n]_20251027_145545/test_basic_auth[--Not authorized\n]_20251027_145545.mp4
INFO     root:base_page.py:76 Navigating to URL: https://the-internet.herokuapp.com/.
INFO     root:base_page.py:78 Navigation completed.
INFO     root:base_page.py:57 Waiting for page to load with indicator ('css selector', 'h1.heading') for 10s.
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
INFO     root:base_page.py:62 Page loaded successfully with indicator ('css selector', 'h1.heading').
INFO     root:basic_auth_page.py:17 .
INFO     root:basic_auth_page.py:25 .
INFO     root:base_page.py:76 Navigating to URL: http://the-internet.herokuapp.com/basic_auth.
INFO     root:base_page.py:78 Navigation completed.
INFO     root:basic_auth_page.py:30 Attempting to get authorization message.
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
WARNING  urllib3.connectionpool:connectionpool.py:327 Connection pool is full, discarding connection: localhost. Connection pool size: 1
ERROR    root:base_page.py:32 Timeout after 10s for locator ('css selector', 'div#content p'): Message: 
Stacktrace:
#0 0x55cacd204fea <unknown>
#1 0x55caccc82d06 <unknown>
#2 0x55cacccd4e6d <unknown>
#3 0x55cacccd5101 <unknown>
#4 0x55caccd236b4 <unknown>
#5 0x55cacccfae3d <unknown>
#6 0x55caccd20b3b <unknown>
#7 0x55cacccfabe3 <unknown>
#8 0x55cacccc72d2 <unknown>
#9 0x55cacccc7f91 <unknown>
#10 0x55cacd1c89e8 <unknown>
#11 0x55cacd1cc84f <unknown>
#12 0x55cacd1afec9 <unknown>
#13 0x55cacd1cd3f5 <unknown>
#14 0x55cacd19574f <unknown>
#15 0x55cacd1f1cc8 <unknown>
#16 0x55cacd1f1ea3 <unknown>
#17 0x55cacd203f83 <unknown>
#18 0x7f4ea049caa4 <unknown>
#19 0x7f4ea0529c6c <unknown>
INFO     root:conftest.py:146 Stopping video recording...
INFO     utils.video_recorder:video_recorder.py:95 Video created: tests_recordings/gw1/test_basic_auth[--Not authorized\n]_20251027_145545/test_basic_auth[--Not authorized\n]_20251027_145545.mp4
INFO     root:conftest.py:102 Quitting driver for browser: chrome.